### ISSUE TITLE
Can't start the service due to java.util.NoSuchElementException

### ISSUE THREAD

**Issue by crlsktr** [oshmoun/QcRilAm#1]
Hi, sorry to bug you. I'm looking at the aospa build that includes this version of QcRilAm. RescueParty keeps shutting down the phone due to repeated crashes of `QcRilAmService`.

The exception that I'm seeing is `java.lang.RuntimeException: Unable to create service com.sony.qcrilam.QcRilAmService: java.util.NoSuchElementException`.

```
07-08 04:06:43.421 29519 29519 E AndroidRuntime: FATAL EXCEPTION: main
07-08 04:06:43.421 29519 29519 E AndroidRuntime: Process: com.sony.qcrilam, PID: 29519
07-08 04:06:43.421 29519 29519 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.sony.qcrilam.QcRilAmService: java.util.NoSuchElementException
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3545)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6697)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: Caused by: java.util.NoSuchElementException
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.os.HwBinder.getService(Native Method)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.os.HwBinder.getService(HwBinder.java:91)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at vendor.qti.hardware.radio.am.V1_0.IQcRilAudio.getService(IQcRilAudio.java:48)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at com.sony.qcrilam.QcRilAmService.addCallbackForSimSlot(QcRilAmService.java:23)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at com.sony.qcrilam.QcRilAmService.onCreate(QcRilAmService.java:52)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3533)
07-08 04:06:43.421 29519 29519 E AndroidRuntime: 	... 8 more
```

I'm willing to debug it but I was wondering if I could get some build instructions in the readme. 
Thanks, and sorry for the disruption.

**Comment by oshmoun** [comment]
there are many reasons why this exception would occur, as this exception is more of a symptom of a prior error, or of a misconfgured device. 
in any case, consider updating to the latest from https://github.com/sonyxperiadev/QcRilAm/tree/q-mr1 as that is where further development is happening
